# Generated by Django 4.2.3 on 2023-07-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('mobileNumber', models.CharField(max_length=13)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('dateOfBirth', models.DateField()),
                ('address', models.TextField()),
                ('profilePhoto', models.ImageField(upload_to='backend/profilePhotos')),
            ],
        ),
    ]
