# Generated by Django 4.2.3 on 2023-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.FileField(null=True, upload_to='backend/profilePhotos'),
        ),
    ]
