# Generated by Django 4.2.3 on 2023-07-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobileNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePhoto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
