# Generated by Django 4.2.3 on 2023-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_user_address_remove_user_creationtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='adminaddress', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='creationTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AddField(
            model_name='user',
            name='emailAddress',
            field=models.EmailField(default='admin@admin.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(null=True, upload_to='backend/profilePhotos'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('QUEER', 'QUEER')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
