# Generated by Django 4.2.3 on 2023-07-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_user_address_alter_user_dateofbirth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=200)),
                ('dishCategoryCourse', models.CharField(choices=[('appetizers', 'Appetizers'), ('entree', 'Entree'), ('desserts', 'Desserts'), ('sides', 'Sides'), ('snacks', 'Snacks')], max_length=200)),
                ('dishCategoryCuisine', models.CharField(choices=[('indian', 'Indian'), ('italian', 'Italian'), ('spanish', 'Spanish'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('states', 'States'), ('british', 'British')], max_length=200)),
                ('dishCategoryDietary', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('nonvegetarian', 'Non Vegetarian'), ('pescatarian', 'Pescatarian')], max_length=200)),
                ('dishCategoryAllergen', models.CharField(choices=[('nut', 'Contains Nuts'), ('shellfish', 'Contains Shellfish'), ('soy', 'Contains Soy'), ('egg', 'Contains Egg')], max_length=200)),
                ('dishCategorySpicenessLevel', models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('spicy', 'Spicy'), ('extraspicy', 'Extra Spicy')], max_length=200)),
                ('dishCategorySeason', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=200)),
                ('dishCategoryDayPart', models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=200)),
                ('dishImage', models.CharField(max_length=200)),
                ('dishDescription', models.CharField(max_length=10000)),
                ('dishRating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dishTotalTime', models.CharField(max_length=20)),
                ('dishPreparationTime', models.CharField(max_length=20)),
                ('dishCookingTime', models.CharField(max_length=20)),
                ('dishCalories', models.CharField(max_length=20)),
                ('dishProteins', models.CharField(max_length=20)),
                ('dishFats', models.CharField(max_length=20)),
                ('dishCarbohydrates', models.CharField(max_length=20)),
                ('dishFibres', models.CharField(max_length=20)),
                ('dishSugar', models.CharField(max_length=20)),
                ('dishSodium', models.CharField(max_length=20)),
                ('dishLastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=200)),
                ('ingredientImage', models.CharField(max_length=200)),
                ('ingredientCategory', models.CharField(choices=[('vegetables', 'Vegetables'), ('mushrooms', 'Mushrooms'), ('fruits', 'Fruits'), ('berries', 'Berries'), ('nutsseeds', 'Nuts N Seeds'), ('cheeses', 'Cheeses'), ('dairy', 'Dairy'), ('dairyfree', 'Dairy Free'), ('eggs', 'Eggs'), ('pasta', 'Pasta'), ('meat', 'Meat'), ('meatsubstitutes', 'Meat Substitutes'), ('poulty', 'Poulty'), ('fish', 'Fish'), ('shellfish', 'Shellfish'), ('herbsspices', 'Herbs N Spices'), ('sugarsweetners', 'Sugar N Sweetners'), ('seasoning', 'Seasonings'), ('baking', 'Baking'), ('grains', 'Grains'), ('legumes', 'Legumes'), ('breads', 'Breads'), ('oilsfats', 'Oils N Fats'), ('dressingsvinegars', 'Dressings N Vinegars'), ('condiments', 'Condiments'), ('canned', 'Canned Foods'), ('saucesspreadsdips', 'Sauces, Spreads N Dips'), ('stewsstocks', 'Stews N Stocks'), ('dessertssweets', 'Desserts N Sweets'), ('alcohol', 'Alcohol'), ('breverages', 'Breverages')], max_length=50)),
                ('ingredientPantryEssentials', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishIngredientQuantity', models.IntegerField()),
                ('dishIngredientQuantityUnit', models.CharField(max_length=200)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dish')),
                ('ingredientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ingredient')),
            ],
        ),
    ]
