# Generated by Django 4.2.3 on 2023-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_dish_ingredient_dishingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dishCategoryDayPart',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishCategorySeason',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all', 'All')], max_length=200),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishImage',
            field=models.FileField(default='https://www.istockphoto.com/vector/hand-drawn-vector-seamless-pattern-with-sketch-dairy-products-on-a-blackboard-gm1224636004-360176253?phrase=black%20and%20white%20dish', max_length=200, upload_to=''),
        ),
    ]
