# Generated by Django 4.2.3 on 2023-07-16 15:25

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_dish_dishcategorydaypart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dishCategoryCourse',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dishCategoryCuisine',
            new_name='Cuisine',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishCategoryAllergen',
            field=models.CharField(choices=[('nut', 'Contains Nuts'), ('shellfish', 'Contains Shellfish'), ('soy', 'Contains Soy'), ('egg', 'Contains Egg'), ('dairy', 'Contains Dairy Products'), ('none', 'None')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(blank=True, default=backend.models.defaultProfile, null=True, upload_to='backend/profilePhotos'),
        ),
    ]
