# Generated by Django 4.2.3 on 2023-07-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_dishcategorycourse_dish_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='Cuisine',
            new_name='cuisine',
        ),
    ]
