# Generated by Django 4.2.3 on 2023-07-20 02:59

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_user_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.FileField(blank=True, default=backend.models.defaultProfile, null=True, upload_to='profilePhotos'),
        ),
    ]
