# Generated by Django 4.2.3 on 2023-07-20 04:45

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_user_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=backend.models.FileField(blank=True, default=backend.models.defaultProfile, null=True, upload_to=''),
        ),
    ]
