# Generated by Django 4.2.3 on 2023-07-20 10:00

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_user_address_remove_user_creationtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='creationTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='emailAddress',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePhoto',
            field=backend.models.FileField(blank=True, default=backend.models.defaultProfile, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
