# Generated by Django 4.2.3 on 2023-07-20 10:07

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_user_address_alter_user_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=backend.models.FileField(blank=True, default=backend.models.defaultProfile, null=True, upload_to='userProfilePhotos/'),
        ),
    ]
