# Generated by Django 4.2.3 on 2023-07-20 11:28

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_user_profilephoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='course',
            new_name='dishcourse',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='cuisine',
            new_name='dishcuisine',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishImage',
            field=backend.models.FileField(blank=True, default=backend.models.defaultDishImage, null=True, upload_to='userProfilePhotos/'),
        ),
    ]
