# Generated by Django 4.2.3 on 2023-07-20 11:28

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_rename_course_dish_dishcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dishImage',
            field=backend.models.FileField(blank=True, default=backend.models.defaultDishImage, null=True, upload_to='dishImages/'),
        ),
    ]
