# Generated by Django 4.2.3 on 2023-07-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_dish_dishimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dishcourse',
            new_name='dishCourse',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dishcuisine',
            new_name='dishCuisine',
        ),
    ]
