# Generated by Django 4.2.3 on 2023-07-20 13:03

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_rename_dishcourse_dish_dishcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientImage',
            field=backend.models.FileField(blank=True, default=backend.models.defaultIngredientImage, null=True, upload_to='ingredientImages/'),
        ),
    ]
