# Generated by Django 4.2.3 on 2023-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_ingredient_ingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientCategory',
            field=models.CharField(choices=[('VEGETABLES', 'VEGETABLES'), ('mushrooms', 'Mushrooms'), ('fruits', 'Fruits'), ('berries', 'Berries'), ('nutsseeds', 'Nuts N Seeds'), ('cheeses', 'Cheeses'), ('dairy', 'Dairy'), ('dairyfree', 'Dairy Free'), ('eggs', 'Eggs'), ('pasta', 'Pasta'), ('meat', 'Meat'), ('meatsubstitutes', 'Meat Substitutes'), ('poulty', 'Poulty'), ('fish', 'Fish'), ('shellfish', 'Shellfish'), ('herbsspices', 'Herbs N Spices'), ('sugarsweetners', 'Sugar N Sweetners'), ('seasoning', 'Seasonings'), ('baking', 'Baking'), ('grains', 'Grains'), ('legumes', 'Legumes'), ('breads', 'Breads'), ('oilsfats', 'Oils N Fats'), ('dressingsvinegars', 'Dressings N Vinegars'), ('condiments', 'Condiments'), ('canned', 'Canned Foods'), ('saucesspreadsdips', 'Sauces, Spreads N Dips'), ('stewsstocks', 'Stews N Stocks'), ('dessertssweets', 'Desserts N Sweets'), ('alcohol', 'Alcohol'), ('breverages', 'Breverages')], max_length=50),
        ),
    ]
