# Generated by Django 4.2.3 on 2023-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_ingredient_ingredientcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientCategory',
            field=models.CharField(choices=[('VEGETABLES', 'VEGETABLES'), ('MUSHROOMS', 'MUSHROOMS'), ('FRUITS', 'FRUITS'), ('BERRIES', 'BERRIES'), ('NUTSNSEEDS', 'NUTS N SEEDS'), ('CHEESES', 'CHEESES'), ('DAIRY', 'DAIRY'), ('DAIRYFREE', 'DAIRY FREE'), ('EGGS', 'EGGS'), ('PASTA', 'PASTA'), ('MEAT', 'MEAT'), ('MEATSUBSTITUTES', 'MEAT SUBSTITUTES'), ('POULTRY', 'POULTRY'), ('FISH', 'FISH'), ('SHELLFISH', 'SHELLFISH'), ('HERBSNSPICES', 'HERBS N SPICES'), ('SUGARSNSWEETNERS', 'SUGARS N SWEETNERS'), ('SEASONINGS', 'SEASONINGS'), ('BAKING', 'BAKING'), ('GRAINS', 'GRAINS'), ('LEGUMES', 'LEGUMES'), ('BREADS', 'BREADS'), ('OILSNFATS', 'OILS N FATS'), ('DRESSINGSNVINEGARS', 'DRESSINGS N VINEGARS'), ('CONDIMENTS', 'CONDIMENTS'), ('CANNED', 'CANNED FOODS'), ('SAUCESNSPREADSNDIPS', 'SAUCES, SPREADS N DIPS'), ('STEWSNSTOCKS', 'STEWS N STOCKS'), ('DESSERTSNSWEETS', 'DESSERTS N SWEETS'), ('ALCOHOL', 'ALCOHOL'), ('BREVERAGES', 'BREVERAGES')], max_length=50),
        ),
    ]
