# Generated by Django 4.2.3 on 2023-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_ingredient_ingredientcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dishVisits',
            field=models.IntegerField(default=0),
        ),
    ]
