# Generated by Django 4.2.3 on 2023-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_dish_dishvisits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='dishIngredientQuantityUnit',
            field=models.CharField(default='', max_length=200),
        ),
    ]
