# Generated by Django 4.2.3 on 2023-07-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_dishingredient_dishingredientquantityunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dishCourse',
            new_name='dishCategoryCourse',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='dishCuisine',
            new_name='dishCategoryCuisine',
        ),
    ]
