# Generated by Django 4.2.3 on 2023-07-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_rename_dishcourse_dish_dishcategorycourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSavedRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeSaved', models.DateTimeField(auto_now=True)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dish')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
