# Generated by Django 4.2.3 on 2023-07-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_usersavedrecipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishStepDescription', models.CharField(max_length=400, null=True)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dish')),
            ],
        ),
    ]
