# Generated by Django 4.2.3 on 2023-07-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_dishstep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userSavedRecipes',
            new_name='UserRatedRecipe',
        ),
        migrations.CreateModel(
            name='UserSavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeSaved', models.DateTimeField(auto_now=True)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dish')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
