# Generated by Django 4.2.3 on 2023-07-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_rename_usersavedrecipes_userratedrecipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratedrecipe',
            old_name='recipeSaved',
            new_name='recipeRated',
        ),
    ]
