# Generated by Django 4.2.3 on 2023-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_userratedrecipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratedrecipe',
            name='rating',
            field=models.CharField(choices=[('THUMBSUP', 'THUMBS UP'), ('THUMBSDOWN', 'THUMBS DOWN')], max_length=10),
        ),
    ]
