# Generated by Django 4.2.3 on 2023-07-30 03:19

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_alter_userratedrecipe_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipDescription', models.CharField(max_length=500)),
                ('userTipImage', backend.models.FileField(blank=True, null=True, upload_to='userTips/')),
                ('recipeTiped', models.DateTimeField(auto_now=True)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dish')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
