# Generated by Django 4.2.3 on 2023-07-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_usertips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTips',
            new_name='UserTip',
        ),
    ]
