# Generated by Django 4.2.3 on 2023-09-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_alter_usersavedrecipe_usersavedrecipecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersavedrecipe',
            old_name='UserSavedRecipeCategory',
            new_name='userSavedRecipeCategory',
        ),
    ]
