# Generated by Django 4.2.3 on 2023-09-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_rename_usersavedrecipecategory_usersavedrecipe_usersavedrecipecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedrecipe',
            name='userSavedRecipeCategory',
            field=models.CharField(choices=[('APPETIZERS', 'APPETIZERS'), ('ENTREE', 'ENTREE'), ('DESSERTS', 'DESSERTS'), ('SIDES', 'SIDES'), ('SNACKS', 'SNACKS')], max_length=200),
        ),
    ]
