# Generated by Django 4.2.3 on 2023-09-06 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_alter_usersavedrecipe_usersavedrecipecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeViewed', models.DateTimeField(auto_now=True)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dish')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
