# Generated by Django 4.2.3 on 2023-09-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_userrecentlyviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecentlyviewed',
            old_name='recipeViewed',
            new_name='recipeViewedTime',
        ),
    ]
