# Generated by Django 4.2.3 on 2023-09-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_rename_recipeviewed_userrecentlyviewed_recipeviewedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientAddedTime', models.DateTimeField(auto_now=True)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dish')),
                ('ingredientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dishingredient')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
