# Generated by Django 4.2.3 on 2023-09-14 02:39

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_userpantry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadImage', backend.models.FileField(blank=True, default=backend.models.defaultDishImage, null=True, upload_to='dishImages/')),
                ('uploadName', models.CharField(max_length=100)),
                ('uploadDescription', models.CharField(max_length=10000)),
                ('creationTime', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
