# Generated by Django 4.2.3 on 2023-09-14 02:59

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_userupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='uploadLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='uploadImage',
            field=backend.models.FileField(blank=True, default=backend.models.defaultDishImage, null=True, upload_to='userUploads/'),
        ),
    ]
