# Generated by Django 4.2.3 on 2023-09-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_userupload_uploadlikes_alter_userupload_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
