# Generated by Django 4.2.3 on 2023-09-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_remove_ingredient_ingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='dishIngredientQuantity',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
