# Generated by Django 4.2.3 on 2023-09-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_alter_dishingredient_dishingredientquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
